### ISSUE TITLE
Duplicate data for : /overall api and area?provinceEng=China !

### ISSUE THREAD

**Issue by redmenIshab** [BlankerL/DXY-COVID-19-Data#53] opened 2020-03-17 08:59 UTC
The "confirmedCount" value for 
https://lab.isaaclin.cn/nCoV/api/area?provinceEng=China  AND
https://lab.isaaclin.cn/nCoV/api/overall?latest=0

is same, Please have a look at it !

**Comment by BlankerL** [comment] 2020-03-18 05:22
Yes, it should be the same. The data of these two APIs are located in different `<span>` on DXY, and DXY provides this entry in both `<span>`, so this project just automatically record them. 

In the database, data of `/nCoV/api/overall` are stored in `DXYOverall`, data of `/nCoV/api/area` are stored in `DXYArea`. 

You can choose either one you would like to use. Specifically, if you do not need the number of critically ill patients (labeled as `seriousCount`) and remarks, you could use `/nCoV/api/area` to cut down the traffic and speed up your request.

**Comment by x5engine** [comment] 2020-03-18 19:16
@BlankerL did you just make a big mistake? current overall confirmed cases are 200K not 81K

**Comment by BlankerL** [comment] 2020-03-18 20:54
> @BlankerL did you just make a big mistake? current overall confirmed cases are 200K not 81K

I don't think so. I just checked the data are they are still 81K. 

```json
{
	"results": [{
		"currentConfirmedCount": 8183,
		"confirmedCount": 81202,
		"suspectedCount": 155,
		"curedCount": 69777,
		"deadCount": 3242,
		"seriousCount": 2622,
		"generalRemark": "1. 3 月 12 日国家卫健委确诊补订遗漏 12 例确诊病例（非 12 日新增），暂无具体省份信息。 2. 浙江省 12 例外省治愈暂无具体省份信息。",
		"abroadRemark": "",
		"remark1": "易感人群：人群普遍易感。老年人及有基础疾病者感染后病情较重，儿童及婴幼儿也有发病",
		"remark2": "潜伏期：一般为 3～7 天，最长不超过 14 天，潜伏期内可能存在传染性，其中无症状病例传染性非常罕见",
		"remark3": "宿主：野生动物，可能为中华菊头蝠",
		"remark4": "",
		"remark5": "",
		"note1": "病毒：SARS-CoV-2，其导致疾病命名 COVID-19",
		"note2": "传染源：新冠肺炎的患者。无症状感染者也可能成为传染源。",
		"note3": "传播途径：经呼吸道飞沫、接触传播是主要的传播途径。气溶胶传播和消化道等传播途径尚待明确。",
		"updateTime": 1584563842956
	}],
	"success": true
}
```

**Comment by BlankerL** [comment] 2020-03-19 17:27
If you think I am wrong, just show me where is the 200K? 

BTW, all the data are extracted from the DXY's website, some time there is a typo because all the data are manually input to their database by their staff, and they are working 24/7 to update the database. Most of the typos will be fixed by them within 15 minutes. 

If you think there is something noise data crawled into the database, please report to BlankerL/DXY-COVID-19-Crawler#34. 

Thumbs Down will never help.

**Closed as completed by BlankerL** 2020-03-19 17:27 UTC
Labels: question
