### ISSUE TITLE
数据接口访问不了

### ISSUE THREAD

**Issue by huang494** [BlankerL/DXY-COVID-19-Data#111] opened 2022-04-11 15:26 UTC
数据接口访问不了
![dd36058415427b198d0c435246d7b69](https://user-images.githubusercontent.com/74822623/162773747-cd625a64-f872-4f10-a692-29d6e991bdb9.png)

**Comment by BlankerL** [comment] 2022-04-19 10:37
Duplicate of BlankerL/DXY-COVID-19-Crawler#135

**Closed as completed by BlankerL** 2022-04-19 10:37 UTC
Labels: duplicate
