### ISSUE TITLE
suspectedCount in DXYArea.json are all 0

### ISSUE THREAD

**Issue by denven** [BlankerL/DXY-COVID-19-Data#35] opened 2020-02-19 07:54 UTC
Not consistent with data other files and it's also  not correct right now.

**Comment by BlankerL** [comment] 2020-02-19 09:34
Ding Xiang Yuan has not published any of province-level or city-level suspectedCount since January 28. I do not check the government published data, but I suppose it is because the Provincial/City-Level Health Commissions do not publish them.

**Comment by BlankerL** [comment] 2020-02-19 09:35
Duplicate of #1

**Closed as completed** 2020-02-19 09:35 UTC
Labels: question
